export const ONBOARDING_WALKTHROUGH_STEPS = [
  {
    part: "MAIN PRACTICE TOOLS",
    eyebrow: "Part 1 · Your study system",
    title: "Start from your home base",
    body: "Overview is your starting point: it surfaces your next study move and keeps the tools you use most within reach.",
    icon: "home",
    tabLabel: "Home",
    detail: "Your daily Blue Blazer launchpad",
    path: "/",
    action: "Look around your home base, then continue when you are ready.",
  },
  {
    part: "MAIN PRACTICE TOOLS",
    eyebrow: "Part 1 · Learn the standard",
    title: "Turn PIs into usable skill",
    body: "Open the PI Study Library to turn performance indicators into plain-English lessons, vocabulary, flashcards, scenarios, and quizzes.",
    icon: "study",
    tabLabel: "PI Study Library",
    detail: "Learn each performance indicator in context",
    path: "/pi-quizlet",
    action: "Open a PI module or use search while this guide stays with you.",
  },
  {
    part: "MAIN PRACTICE TOOLS",
    eyebrow: "Part 1 · Practice deliberately",
    title: "Strengthen one cluster at a time",
    body: "Use Practice to focus on Marketing, Business, Finance, or Hospitality & Tourism questions, then review why each answer works.",
    icon: "practice",
    tabLabel: "Practice",
    detail: "Question banks organized by career cluster",
    path: "/practice",
    action: "Choose a cluster card or browse questions, then return here to continue.",
  },
  {
    part: "CHAPTER TOOLS",
    eyebrow: "Part 2 · Choose your event",
    title: "Connect preparation to your event",
    body: "Open Events & Community to explore competitive events, view every applicable PI for an event, and open a complete PI module from its study path.",
    icon: "community",
    tabLabel: "Events & Community",
    detail: "Event selection, PI pathways, and chapter resources",
    path: "/events",
    action: "Expand an event and open its PI study path while this guide stays in the corner.",
  },
  {
    part: "CHAPTER TOOLS",
    eyebrow: "Part 2 · Stay chapter-ready",
    title: "Keep up with your chapter",
    body: "The Chapter section keeps Calendar, Announcements, Discussion Posts, Volunteer Sign-Ups, and Feedback organized in one place.",
    icon: "community",
    tabLabel: "Chapter",
    detail: "Events, deadlines, communication, and involvement",
    path: "/calendar",
    action: "Review the calendar, then use the Chapter section whenever you need chapter information or a way to contribute.",
  },
  {
    part: "BLUE BUCKS",
    eyebrow: "Part 3 · Earn as you learn",
    title: "Meet Blue Bucks",
    body: "Blue Bucks are virtual in-app rewards for correct first attempts and follow-up corrections; each question can reward you only once. They are used only in Blue Blazer simulation features and have no cash value.",
    icon: "blueBucks",
    tabLabel: "Blue Bucks",
    detail: "Virtual rewards for consistent, honest practice",
    path: "/banking",
    action: "Open Banking to choose a Study Card and see how your study rewards support your Blue Blazer simulation experience.",
  },
  {
    part: "BLUE BUCKS",
    eyebrow: "Part 3 · Put your preparation to work",
    title: "Turn practice into a plan",
    body: "Use Mock Exams to identify weak points, then return to the exact PI and Practice tools that will strengthen your next attempt.",
    icon: "readiness",
    tabLabel: "Mock Exams & Progress",
    detail: "Measure readiness and choose your next move",
    path: "/chapter-mock-exam",
    action: "Review the two exam options and your progress history before finishing your tour.",
  },
] as const;

export type OnboardingWalkthroughIcon = (typeof ONBOARDING_WALKTHROUGH_STEPS)[number]["icon"];
