export const ONBOARDING_WALKTHROUGH_STEPS = [
  {
    part: "MAIN PRACTICE TOOLS",
    eyebrow: "Part 1 · Your command center",
    title: "Start from your study plan",
    body: "Overview brings your real practice record, selected event, Blue Bucks accounts, BBX status, and chapter updates together so you can choose the right next move.",
    icon: "home",
    tabLabel: "Overview",
    detail: "Your live study and chapter command center",
    path: "/",
    action: "Use this page to decide whether your next move is PI study, practice, an exam, chapter activity, or a financial simulation tool.",
  },
  {
    part: "MAIN PRACTICE TOOLS",
    eyebrow: "Part 1 · Learn the standard",
    title: "Build skills with PI Study Library",
    body: "Every Performance Indicator module combines a plain-English lesson, business explanation, vocabulary, interactive flashcards, quick review, a 15-question quiz, scenarios, related concepts, and teach-back practice.",
    icon: "study",
    tabLabel: "PI Study Library",
    detail: "Complete PI learning modules for event preparation",
    path: "/pi-quizlet",
    action: "Search for a PI, filter by your event, or open a module and work through each activity in order.",
  },
  {
    part: "MAIN PRACTICE TOOLS",
    eyebrow: "Part 1 · Practice deliberately",
    title: "Practice one cluster at a time",
    body: "Choose Marketing, Business Management & Administration, Finance, or Hospitality & Tourism, answer exam-style questions, save questions for later, and use the explanation to learn from each result.",
    icon: "practice",
    tabLabel: "Practice",
    detail: "39,000 cluster-aligned questions with answer tracking",
    path: "/practice",
    action: "Choose a cluster card, begin a question set, and save any question you want to revisit after the session.",
  },
  {
    part: "MAIN PRACTICE TOOLS",
    eyebrow: "Part 1 · Measure readiness",
    title: "Turn weak points into a study guide",
    body: "Individual Mock Exams stay focused on one selected cluster, use available questions, and return concept and PI accuracy so your next study guide targets what will add points.",
    icon: "readiness",
    tabLabel: "Mock Exams",
    detail: "Cluster-focused exam practice and targeted PI recovery",
    path: "/mock-exams",
    action: "Start an individual mock exam when you are ready for a full readiness check, then open the generated study guide after you finish.",
  },
  {
    part: "MAIN PRACTICE TOOLS",
    eyebrow: "Part 1 · Compare your momentum",
    title: "See accurate chapter progress",
    body: "Leaderboard uses recorded question results to show chapter rankings and cluster performance. It reflects actual practice activity rather than a separate simulated score.",
    icon: "leaderboard",
    tabLabel: "Leaderboard",
    detail: "Chapter rankings based on recorded practice performance",
    path: "/leaderboard",
    action: "Review the overall and cluster leaderboards to understand where your consistent practice is taking you.",
  },
  {
    part: "MAIN PRACTICE TOOLS",
    eyebrow: "Part 1 · Rehearse with guidance",
    title: "Use AI Study & Roleplay",
    body: "AI Study & Roleplay gives you a full-page workspace for preparation. Use the available study, roleplay, and written-event coaching tools to rehearse, structure ideas, and improve your delivery.",
    icon: "ai",
    tabLabel: "AI Study & Roleplay",
    detail: "Full-screen AI preparation workspaces",
    path: "/speech-ai",
    action: "Open the AI workspace, then choose the roleplay or written-event tool that matches the way you are preparing.",
  },
  {
    part: "CHAPTER TOOLS",
    eyebrow: "Part 2 · Choose your event",
    title: "Explore events and their PI paths",
    body: "Events & Community lists every catalog event and its applicable Performance Indicators. Expand an event to review the full PI pathway and open an aligned module directly from the panel.",
    icon: "events",
    tabLabel: "Events & Community",
    detail: "Event exploration with complete applicable PI pathways",
    path: "/events",
    action: "Expand the event you are considering, inspect its PI pathway, and open the linked PI Study Library module when you find a skill to build.",
  },
  {
    part: "CHAPTER TOOLS",
    eyebrow: "Part 2 · Plan ahead",
    title: "Keep deadlines in view",
    body: "Calendar is your chapter schedule for events, deadlines, meetings, and competition planning. It helps you turn preparation into a timeline rather than a last-minute task.",
    icon: "calendar",
    tabLabel: "Calendar",
    detail: "Chapter events, deadlines, and planning dates",
    path: "/calendar",
    action: "Review upcoming dates before setting your study plan, especially when a competition or chapter deadline is approaching.",
  },
  {
    part: "CHAPTER TOOLS",
    eyebrow: "Part 2 · Stay informed",
    title: "Read chapter announcements",
    body: "Announcements is the chapter’s official update space for information members need to know. Check it regularly so planning changes and opportunities do not get missed.",
    icon: "announcements",
    tabLabel: "Announcements",
    detail: "Official chapter updates and notices",
    path: "/announcements",
    action: "Open the latest announcement and use this page whenever you need the chapter’s current information.",
  },
  {
    part: "CHAPTER TOOLS",
    eyebrow: "Part 2 · Learn together",
    title: "Join the discussion",
    body: "Discussion Posts gives members a dedicated space to ask questions, share preparation ideas, and learn from teammates across the chapter.",
    icon: "discussions",
    tabLabel: "Discussion Posts",
    detail: "Member questions, preparation ideas, and peer support",
    path: "/discussions",
    action: "Read an active discussion or post a useful question when you need help preparing.",
  },
  {
    part: "CHAPTER TOOLS",
    eyebrow: "Part 2 · Contribute beyond competition",
    title: "Track volunteer opportunities",
    body: "Volunteer Sign-Ups organizes chapter opportunities to contribute, build service experience, and keep your DECA involvement visible in one place.",
    icon: "volunteer",
    tabLabel: "Volunteer Sign-Ups",
    detail: "Chapter service opportunities and sign-ups",
    path: "/volunteer",
    action: "Review available opportunities and sign up when a chapter activity fits your schedule.",
  },
  {
    part: "CHAPTER TOOLS",
    eyebrow: "Part 2 · Improve the chapter",
    title: "Send feedback that reaches the team",
    body: "Feedback is where you can send a clear note about the platform or chapter experience. Submitted feedback is routed so the chapter team can review and respond.",
    icon: "feedback",
    tabLabel: "Feedback",
    detail: "A direct route for product and chapter feedback",
    path: "/feedback",
    action: "Open Feedback whenever you find an issue, have an idea, or need to share a constructive suggestion.",
  },
  {
    part: "BLUE BUCKS",
    eyebrow: "Part 3 · Earn through learning",
    title: "Earn Blue Bucks with real practice",
    body: "Blue Bucks are virtual in-app rewards. Correct first attempts and corrected answers can earn rewards once per question, and eligible Blue’s News reading can earn additional rewards. They have no cash value.",
    icon: "blueBucks",
    tabLabel: "Blue Bucks",
    detail: "Virtual rewards for active, honest learning",
    path: "/practice",
    action: "Answer practice questions carefully: your learning activity—not repeated attempts—creates Blue Bucks rewards.",
  },
  {
    part: "BLUE BUCKS",
    eyebrow: "Part 3 · Use your accounts",
    title: "Blue Bucks arrive in Checking",
    body: "Earned Blue Bucks credit your Banking Checking balance automatically—there is no manual deposit step. Banking also shows Savings with its 7% monthly simulation return, your Investment Account, transactions, credit score, and functional Study Cards.",
    icon: "banking",
    tabLabel: "Banking & Cards",
    detail: "Checking, Savings, Investment, transactions, and Study Cards",
    path: "/banking",
    action: "Open Banking to see your Checking balance, choose a Study Card, move available funds between your simulation accounts, and review its account tools.",
  },
  {
    part: "BLUE BUCKS",
    eyebrow: "Part 3 · Read the market story",
    title: "Read Blue’s News for rewards",
    body: "Blue’s News publishes fictional market stories for the BBX simulation. Read new eligible stories to collect their Blue Bucks reward in Checking, then infer market effects from the story rather than a displayed price magnitude.",
    icon: "news",
    tabLabel: "Blue’s News",
    detail: "Fictional market stories with eligible reading rewards",
    path: "/blues-news",
    action: "Open unread stories, read the context, and watch your Checking balance receive any eligible Blue Bucks reward.",
  },
  {
    part: "BLUE BUCKS",
    eyebrow: "Part 3 · Run your simulation",
    title: "Use BBX with your Investment Account",
    body: "BBX is a fictional stock-market simulation. Its available buying power is your Banking Investment Account balance, and its portfolio, market board, charts, and news tools use stored simulation data—not real money or real securities.",
    icon: "market",
    tabLabel: "Stock Market (BBX)",
    detail: "Fictional market board, portfolio, charts, and learning tools",
    path: "/blue-market",
    action: "Open BBX after funding your Investment Account, explore the market board and portfolio, then return to your study plan when you are ready.",
  },
] as const;

export type OnboardingWalkthroughIcon = (typeof ONBOARDING_WALKTHROUGH_STEPS)[number]["icon"];
