type TourPart = "MAIN PRACTICE TOOLS" | "CHAPTER TOOLS" | "BLUE BUCKS";

export const ONBOARDING_WALKTHROUGH_STEPS = [
  { part: "MAIN PRACTICE TOOLS", eyebrow: "Part 1 · Your command center", title: "Start from your Overview", body: "Overview brings your selected event, study path, practice history, personalized readiness, Blue Bucks accounts, and chapter updates together so you can choose the right next move.", icon: "home", tabLabel: "Overview", detail: "Your live study and chapter command center", path: "/", action: "Use the study path to move directly into the one activity that will help your next competition milestone." },
  { part: "MAIN PRACTICE TOOLS", eyebrow: "Part 1 · Choose a direction", title: "Set your focused DECA event", body: "Events helps you compare official competitive events, select the event you are preparing for, and launch the event finder when you are still deciding. Your choice personalizes PI study, readiness, and the roadmap.", icon: "events", tabLabel: "Events & Event Finder", detail: "Event selection and competition resources", path: "/events", action: "Choose Select this event when you are ready, or start the event finder to narrow your options." },
  { part: "MAIN PRACTICE TOOLS", eyebrow: "Part 1 · Learn the standard", title: "Study the PIs that matter", body: "PI Study Library filters to your focused event and keeps each module concise: main ideas, interactive flashcards, a 15-question quiz, and business scenarios. Mastery updates your preparation data.", icon: "study", tabLabel: "PI Study Library", detail: "Event-relevant performance indicator learning", path: "/pi-quizlet", action: "Search for a Performance Indicator, open its module, and work through each active practice element." },
  { part: "MAIN PRACTICE TOOLS", eyebrow: "Part 1 · Practice deliberately", title: "Build accuracy in Practice", body: "Practice uses cluster-aligned DECA questions, explanations, saved questions, and one-time Blue Bucks rewards for qualifying correct work. The tested-for-your-event indicator keeps the set relevant.", icon: "practice", tabLabel: "Practice", detail: "Focused question sets and explanations", path: "/practice", action: "Choose a cluster, answer carefully, and use explanations to turn misses into a study plan." },
  { part: "MAIN PRACTICE TOOLS", eyebrow: "Part 1 · Measure readiness", title: "Take the right Mock Exam", body: "Individual Mock Exams are always available and focus on one cluster. Chapter Mock Exams appear only when an administrator opens a timed window; both identify weak concepts and PIs for follow-up study.", icon: "mockExam", tabLabel: "Mock Exams", detail: "Individual and chapter-controlled readiness checks", path: "/mock-exams", action: "Take an individual exam for a personal diagnostic, then use its PI study guide to focus your next sessions." },
  { part: "MAIN PRACTICE TOOLS", eyebrow: "Part 1 · Build a deliverable", title: "Use your Project Workspace", body: "Written and pitch-focused events can use Project Workspace to organize the work that supports your competition deliverable before it is ready for advisor review.", icon: "workspace", tabLabel: "Project Workspace", detail: "Written-event and pitch preparation workspace", path: "/project-workspace", action: "Document your project scope, research, evidence, and next drafting step as you prepare." },
  { part: "MAIN PRACTICE TOOLS", eyebrow: "Part 1 · Rehearse with evidence", title: "Practice with AI Study & Roleplay", body: "The native AI workspaces support scenario practice, recorded roleplays, transcription, PI evidence, delivery coaching, written-event materials, and transparent feedback. They are practice tools, not competition submissions.", icon: "ai", tabLabel: "AI Study & Roleplay", detail: "Native roleplay and written-event coaching", path: "/speech-ai", action: "Choose the roleplay or written-event workspace that matches your event, then keep the evidence-based feedback for your next attempt." },
  { part: "MAIN PRACTICE TOOLS", eyebrow: "Part 1 · Follow the plan", title: "Use your adaptive Timeline", body: "My Timeline turns your selected event, chapter dates, PI mastery, and focused practice into a measured weekly roadmap. Progress refreshes as you complete real work, while fixed chapter deadlines remain protected.", icon: "timeline", tabLabel: "My Timeline", detail: "Adaptive weekly roadmap and milestone readiness", path: "/timeline", action: "Start with the highlighted next action; expand readiness details only when you need the factor-by-factor view." },
  { part: "MAIN PRACTICE TOOLS", eyebrow: "Part 1 · See your progress", title: "Keep your Profile current", body: "Profile brings together your study progress, event focus, account snapshot, selected avatar, theme, and achievements. Use Settings when you need to change your event or personalize the experience.", icon: "profile", tabLabel: "Profile & Settings", detail: "Personal progress, event selection, themes, and achievements", path: "/profile", action: "Review your progress tabs, then use Event Selection or Settings when your preparation focus changes." },
  { part: "MAIN PRACTICE TOOLS", eyebrow: "Part 1 · Ask for help", title: "Use Direct Messages and Blazer Buddy", body: "Direct Messages connects you with chapter members. Blazer Buddy provides guided help, study tips, and credit-score refresh notices in the same conversation space.", icon: "messages", tabLabel: "Direct Messages", detail: "Member messaging and guided Blazer Buddy support", path: "/", action: "Use the blue message control to open conversations, ask a focused question, or review Blazer Buddy guidance." },

  { part: "CHAPTER TOOLS", eyebrow: "Part 2 · Plan with your chapter", title: "Keep the Calendar in view", body: "Calendar collects chapter events, deadlines, meetings, and competition planning. It is the chapter-wide counterpart to your personal Timeline.", icon: "calendar", tabLabel: "Calendar", detail: "Chapter events, deadlines, and planning dates", path: "/calendar", action: "Review upcoming dates before committing to a study block or signing up for an opportunity." },
  { part: "CHAPTER TOOLS", eyebrow: "Part 2 · Stay informed", title: "Read Announcements", body: "Announcements is the official update channel for chapter information, schedule changes, preparation reminders, and opportunities.", icon: "announcements", tabLabel: "Announcements", detail: "Official chapter updates and notices", path: "/announcements", action: "Open the most recent announcement whenever you need the chapter’s current information." },
  { part: "CHAPTER TOOLS", eyebrow: "Part 2 · Learn together", title: "Join Discussion Posts", body: "Discussion Posts gives members a space to ask preparation questions, share ideas, and reply to teammates. Your own posts and replies appear immediately after sending.", icon: "discussions", tabLabel: "Discussion Posts", detail: "Member questions, replies, and peer support", path: "/discussions", action: "Read an active thread or post a useful question when you need perspective from the chapter." },
  { part: "CHAPTER TOOLS", eyebrow: "Part 2 · Contribute", title: "Find Volunteer Sign-Ups", body: "Volunteer Sign-Ups lists chapter opportunities, available spaces, and offered hours so service activity stays organized alongside competition preparation.", icon: "volunteer", tabLabel: "Volunteer Sign-Ups", detail: "Chapter service opportunities and offered hours", path: "/volunteer", action: "Review open opportunities and sign up for the activity that fits your schedule." },
  { part: "CHAPTER TOOLS", eyebrow: "Part 2 · Improve Blue Blazer", title: "Send useful Feedback", body: "Feedback gives you a direct way to report an issue, request an improvement, or share a constructive idea with the chapter platform team.", icon: "feedback", tabLabel: "Feedback", detail: "Product and chapter feedback channel", path: "/feedback", action: "Describe what happened, where it happened, and what would make the experience clearer." },
  { part: "CHAPTER TOOLS", eyebrow: "Part 2 · Submit with context", title: "Manage your Portfolio work", body: "Portfolio Upload shows checkpoints assigned to you or your team, their due dates, version history, real upload processing status, advisor feedback, and evidence-bound evaluation results when released.", icon: "portfolio", tabLabel: "My Portfolio", detail: "Checkpoint-aware private submissions and review history", path: "/portfolio-upload", action: "Open the relevant checkpoint, upload a new version when it is ready, and use advisor feedback to guide the next revision." },

  { part: "BLUE BUCKS", eyebrow: "Part 3 · Earn through learning", title: "Earn Blue Bucks responsibly", body: "Blue Bucks are virtual in-app rewards. Qualifying correct practice, corrected answers, discussions, and eligible Blue’s News reading can earn a credit once for its recorded action. They have no cash value.", icon: "blueBucks", tabLabel: "Blue Bucks", detail: "Virtual rewards for active, honest learning", path: "/practice", action: "Focus on understanding each answer—the durable reward ledger records each eligible action only once." },
  { part: "BLUE BUCKS", eyebrow: "Part 3 · Use your accounts", title: "Understand Banking & Cards", body: "Earned Blue Bucks credit Checking automatically. Banking shows Checking, Savings with its 7% monthly simulation return, the Investment Account, transaction activity, credit-building actions, Study Cards, and current achievements—without a debt dashboard.", icon: "banking", tabLabel: "Banking & Cards", detail: "Checking, Savings, Investment, cards, and achievements", path: "/banking", action: "Review your balances, choose a Study Card, and move only available simulation funds between accounts when you have a purpose." },
  { part: "BLUE BUCKS", eyebrow: "Part 3 · Read the market story", title: "Read Blue’s News", body: "Blue’s News publishes fictional BBX market stories. Read eligible new stories to collect their Blue Bucks reward in Checking, then infer possible market effects from the context instead of a displayed price magnitude.", icon: "news", tabLabel: "Blue’s News", detail: "Fictional market stories with eligible reading rewards", path: "/blues-news", action: "Open unread stories, read the context, and watch Checking for any eligible reward." },
  { part: "BLUE BUCKS", eyebrow: "Part 3 · Run the simulation", title: "Use BBX deliberately", body: "BBX is a fictional stock-market simulation. Your Banking Investment Account supplies its buying power, while the market board, portfolio, charts, learning tools, and news use stored simulation data—not real money or securities.", icon: "market", tabLabel: "Stock Market (BBX)", detail: "Fictional market board, portfolio, charts, and learning tools", path: "/blue-market", action: "Fund your Investment Account first, then use the BBX navigation to inspect the market board, portfolio, news, and learning views." },
  { part: "BLUE BUCKS", eyebrow: "Part 3 · See sustained progress", title: "Read the Blue Bucks Leaderboard", body: "Leaderboard ranks chapter members by live Blue Bucks net worth: Checking + Savings + Investment. Practice accuracy, debt, credit limits, and percentage investment returns do not change placement.", icon: "leaderboard", tabLabel: "Leaderboard", detail: "Chapter net-worth rankings from actual account balances", path: "/leaderboard", action: "Compare the three account balances behind each rank, then return to Banking or practice to build your own sustainable progress." },
] as const;

const ADMIN_STEPS = [
  { part: "CHAPTER TOOLS", eyebrow: "Chapter administration · Member support", title: "Manage members and portfolios", body: "Member Management is the chapter advisor workspace for roster support, teams, portfolio checkpoints, shared submissions, reviews, chapter progress, and advisor decisions on integrity findings.", icon: "members", tabLabel: "Member Management", detail: "Rosters, teams, portfolios, checkpoints, and reviews", path: "/chapter/members", action: "Use the sub-tabs to review member progress, publish checkpoints, inspect submissions, and release advisor feedback deliberately." },
  { part: "CHAPTER TOOLS", eyebrow: "Chapter administration · Controls", title: "Run chapter systems", body: "Chapter Management contains administrator controls for chapter-wide configurations, mock-exam availability, BBX simulation settings, and other operational tools that members do not manage.", icon: "management", tabLabel: "Chapter Management", detail: "Chapter-wide administrative controls", path: "/admin", action: "Use these controls only when you are making a deliberate chapter decision, then confirm the member-facing result." },
] as const;

const SUPER_ADMIN_STEP = { part: "CHAPTER TOOLS", eyebrow: "Super administrator · Diagnostics", title: "Inspect chapter diagnostics", body: "Chapter Diagnostics gives designated super administrators visibility into school-level activity, roster, accuracy, and usage signals across the platform.", icon: "diagnostics", tabLabel: "Chapter Diagnostics", detail: "Cross-chapter platform diagnostic workspace", path: "/super-admin/diagnostics", action: "Select a school code before reviewing diagnostic signals, and use the information to support—not surveil—chapter improvement." } as const;

export function getOnboardingWalkthroughSteps(role?: string | null) {
  if (role === "super_admin") return [...ONBOARDING_WALKTHROUGH_STEPS, ...ADMIN_STEPS, SUPER_ADMIN_STEP];
  if (role === "admin") return [...ONBOARDING_WALKTHROUGH_STEPS, ...ADMIN_STEPS];
  return ONBOARDING_WALKTHROUGH_STEPS;
}

export type OnboardingWalkthroughIcon = (ReturnType<typeof getOnboardingWalkthroughSteps>)[number]["icon"];
