import { useEffect, useMemo, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Activity, BarChart3, Building2, ChartNoAxesCombined, Eye, MousePointerClick, ShieldCheck, Users } from "lucide-react";

const DIAGNOSTIC_EMAILS = new Set(["sahan.mallampati@gmail.com", "rtbi2179@gmail.com"]);

function Metric({ label, value, note, icon: Icon }: { label: string; value: string | number; note: string; icon: typeof Users }) {
  return <article className="editorial-panel p-4"><div className="flex items-start justify-between gap-3"><div><p className="data-label">{label}</p><p className="mt-2 font-data text-3xl font-bold text-white">{value}</p><p className="mt-1 text-xs text-white/55">{note}</p></div><span className="rounded-lg border border-blue-300/20 bg-blue-500/10 p-2 text-blue-200"><Icon className="h-4 w-4" /></span></div></article>;
}

export default function SuperAdminDiagnostics() {
  const { user } = useAuth();
  const isDesignated = user?.role === "super_admin" && Boolean(user.email && DIAGNOSTIC_EMAILS.has(user.email.toLowerCase()));
  const chaptersQuery = trpc.superAdminDiagnostics.listChapters.useQuery(undefined, { enabled: isDesignated });
  const [schoolCode, setSchoolCode] = useState("");
  useEffect(() => { if (!schoolCode && chaptersQuery.data?.[0]) setSchoolCode(chaptersQuery.data[0]); }, [chaptersQuery.data, schoolCode]);
  const input = useMemo(() => ({ schoolCode }), [schoolCode]);
  const chapterQuery = trpc.superAdminDiagnostics.getChapter.useQuery(input, { enabled: isDesignated && Boolean(schoolCode), staleTime: 30_000 });

  if (!isDesignated) return <div className="page-shell"><main className="page-content"><div className="rounded-2xl border border-red-400/25 bg-red-500/10 p-6 text-red-100"><ShieldCheck className="mb-3 h-6 w-6" /><h1 className="text-xl font-semibold">Diagnostics access is restricted</h1><p className="mt-2 text-sm text-red-100/75">This panel is available only to the designated Blue Blazer super administrators.</p></div></main></div>;
  const data = chapterQuery.data;
  return <div className="page-shell"><main className="page-content max-w-7xl"><header className="banking-hero"><div><p className="page-eyebrow">Designated super admin workspace</p><h1 className="page-title mt-2">Chapter Diagnostics</h1><p className="page-intro mt-3">Inspect real chapter roster, learning outcomes, operational activity, and privacy-bounded website use by school code.</p></div><label className="min-w-56"><span className="data-label">School code</span><select value={schoolCode} onChange={(event) => setSchoolCode(event.target.value)} className="mt-2 min-h-11 w-full rounded-lg border border-white/15 bg-slate-950 px-3 text-sm text-white focus:border-blue-300 focus:outline-none"><option value="">Select a chapter</option>{chaptersQuery.data?.filter((code): code is string => Boolean(code)).map((code) => <option key={code} value={code}>{code}</option>)}</select></label></header>
    {!schoolCode || chapterQuery.isLoading ? <div className="loading-state">Loading chapter diagnostics…</div> : chapterQuery.error ? <div className="rounded-xl border border-red-400/25 bg-red-500/10 p-4 text-sm text-red-100">{chapterQuery.error.message}</div> : data ? <>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Roster" value={data.summary.memberCount} note={`${data.summary.activeLast7Days} active in 7 days`} icon={Users} /><Metric label="Learning accuracy" value={`${data.summary.accuracy}%`} note={`${data.summary.questionsAnswered.toLocaleString()} answers`} icon={BarChart3} /><Metric label="Page views" value={data.summary.totalViews.toLocaleString()} note={`${data.summary.viewsLast30Days} in 30 days`} icon={Eye} /><Metric label="Control clicks" value={data.summary.totalClicks.toLocaleString()} note={`${data.summary.clicksLast30Days} in 30 days`} icon={MousePointerClick} /></section>
      <section className="mt-6 grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><article className="editorial-panel overflow-hidden"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div><p className="data-label">Chapter roster</p><h2 className="section-heading mt-1">Member readiness</h2></div><span className="text-xs text-white/50">Accuracy from recorded answers</span></div><div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left text-sm"><thead className="border-b border-white/10 bg-white/[0.03] text-xs text-white/55"><tr><th className="px-5 py-3">Member</th><th className="px-4 py-3">Event</th><th className="px-4 py-3">Questions</th><th className="px-4 py-3">Accuracy</th><th className="px-4 py-3">Last activity</th></tr></thead><tbody>{data.roster.map((member) => <tr key={member.id} className="border-b border-white/[0.06] text-white/80"><td className="px-5 py-3"><p className="font-medium text-white">{member.name}</p><p className="mt-0.5 text-xs text-white/45">{member.role} · {member.email ?? "no email"}</p></td><td className="px-4 py-3 text-white/65">{member.focusedEvent ?? "Not selected"}</td><td className="px-4 py-3 font-data">{member.questionsAnswered}</td><td className="px-4 py-3 font-data">{member.accuracy}%</td><td className="px-4 py-3 text-xs text-white/60">{member.lastActiveAt ? new Date(member.lastActiveAt).toLocaleString() : "No recorded activity"}</td></tr>)}</tbody></table></div></article>
        <div className="space-y-6"><article className="editorial-panel p-5"><p className="data-label">Chapter operations</p><h2 className="section-heading mt-1">Live records</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between gap-4"><dt className="text-white/60">Practice days</dt><dd className="font-data text-white">{data.summary.practiceDays}</dd></div><div className="flex justify-between gap-4"><dt className="text-white/60">Study sessions</dt><dd className="font-data text-white">{data.summary.studySessions}</dd></div><div className="flex justify-between gap-4"><dt className="text-white/60">Chapter exams completed</dt><dd className="font-data text-white">{data.summary.completedChapterExams}</dd></div><div className="flex justify-between gap-4"><dt className="text-white/60">Exam review flags</dt><dd className="font-data text-white">{data.summary.suspiciousExamFlags}</dd></div><div className="flex justify-between gap-4"><dt className="text-white/60">Open feedback items</dt><dd className="font-data text-white">{data.summary.unresolvedFeedback}</dd></div></dl></article><article className="editorial-panel p-5"><p className="data-label">Website use</p><h2 className="section-heading mt-1">Most viewed routes</h2><div className="mt-4 space-y-2">{data.topViews.length ? data.topViews.map((entry) => <div key={entry.path} className="flex justify-between gap-3 rounded-lg bg-white/[0.03] px-3 py-2 text-sm"><span className="truncate text-white/70">{entry.path}</span><span className="font-data text-white">{entry.count}</span></div>) : <p className="text-sm leading-6 text-white/55">First-party page-view tracking begins after this release. Existing learning and roster diagnostics above are already based on stored activity.</p>}</div><h3 className="mt-5 text-sm font-semibold text-white">Most used controls</h3><div className="mt-2 space-y-2">{data.topClicks.length ? data.topClicks.map((entry) => <div key={entry.label} className="flex justify-between gap-3 rounded-lg bg-white/[0.03] px-3 py-2 text-sm"><span className="truncate text-white/70">{entry.label}</span><span className="font-data text-white">{entry.count}</span></div>) : <p className="text-sm leading-6 text-white/55">Control-click tracking begins after this release and stores only button or link labels, never member-entered content.</p>}</div></article></div></section>
      <p className="mt-5 flex items-start gap-2 text-xs leading-5 text-white/50"><Activity className="mt-0.5 h-4 w-4 shrink-0 text-blue-300" />Views and clicks are first-party authenticated interaction records. They exclude message content, answers, form values, and other member-entered data.</p>
    </> : null}</main></div>;
}
