import { BadgeCheck, BookOpen, BriefcaseBusiness, CheckCircle2, ChevronRight, Flame, Loader2, Medal, Sparkles, Target, Trophy } from "lucide-react";
import { trpc } from "@/lib/trpc";

const ICONS = { "first-step": BookOpen, "practice-builder": Target, "precision-practice": CheckCircle2, consistency: Flame, "knowledge-keeper": Medal, "event-ready": BriefcaseBusiness, "portfolio-starter": Trophy } as const;
const TIER_STYLE = { bronze: { shell: "border-amber-500/25 bg-[linear-gradient(145deg,rgba(180,83,9,.17),rgba(15,23,42,.55))]", mark: "bg-amber-500/20 text-amber-100", bar: "bg-gradient-to-r from-amber-700 to-amber-300" }, silver: { shell: "border-slate-200/20 bg-[linear-gradient(145deg,rgba(148,163,184,.16),rgba(15,23,42,.55))]", mark: "bg-slate-200/15 text-slate-50", bar: "bg-gradient-to-r from-slate-500 to-slate-100" }, gold: { shell: "border-yellow-300/30 bg-[linear-gradient(145deg,rgba(250,204,21,.18),rgba(15,23,42,.55))]", mark: "bg-yellow-300/15 text-yellow-50", bar: "bg-gradient-to-r from-amber-500 via-yellow-300 to-yellow-100" } } as const;

export function AchievementTierPanel() {
  const summary = trpc.achievements.getSummary.useQuery();
  if (summary.isLoading) return <section id="achievements" role="tabpanel" className="rounded-2xl border border-white/10 bg-slate-950/65 p-10 text-center shadow-[0_16px_42px_oklch(0_0_0/0.2)]"><Loader2 className="mx-auto h-6 w-6 animate-spin text-blue-300" /><p className="mt-3 text-sm text-white/60">Loading your achievement collection…</p></section>;
  if (!summary.data) return <section id="achievements" role="tabpanel" className="rounded-2xl border border-white/10 bg-slate-950/65 p-8"><h2 className="text-2xl font-semibold text-white">Achievements</h2><p className="mt-2 text-sm text-white/60">Achievement progress is temporarily unavailable. Please try again shortly.</p></section>;
  const { achievements, earnedCount, tierCount, nextUnlock } = summary.data;
  const earnedPercent = tierCount ? Math.round((earnedCount / tierCount) * 100) : 0;
  return <section id="achievements" role="tabpanel" className="overflow-hidden rounded-2xl border border-white/10 bg-slate-950/65 shadow-[0_16px_42px_oklch(0_0_0/0.2)]"><header className="border-b border-white/10 bg-[radial-gradient(circle_at_85%_0%,rgba(59,130,246,.2),transparent_36%),linear-gradient(140deg,rgba(15,23,42,.8),rgba(3,7,18,.92))] p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-3"><span className="inline-flex h-11 w-11 items-center justify-center rounded-xl border border-blue-300/20 bg-blue-400/10 text-blue-100"><Medal className="h-5 w-5" /></span><div><p className="data-label text-blue-200/75">Your collection</p><h2 className="mt-1 text-2xl font-semibold text-white">Achievements</h2></div></div><p className="mt-4 max-w-2xl text-sm leading-6 text-white/60">Bronze, Silver, and Gold tiers are verified from recorded Blue Blazer activity. Each milestone stays visible so you always know the next meaningful goal.</p></div><div className="min-w-40 rounded-xl border border-blue-300/20 bg-slate-950/45 p-4"><p className="data-label text-blue-100/70">Tiers earned</p><p className="mt-2 text-2xl font-semibold text-white">{earnedCount}<span className="text-base font-medium text-white/45"> / {tierCount}</span></p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-blue-400" style={{ width: `${earnedPercent}%` }} /></div><p className="mt-2 text-xs text-blue-100/75">{earnedPercent}% unlocked</p></div></div></header>
  {nextUnlock && <div className="mx-5 mt-5 flex flex-col gap-4 rounded-xl border border-blue-300/20 bg-blue-400/[0.07] p-4 sm:mx-7 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><Sparkles className="mt-0.5 h-5 w-5 shrink-0 text-blue-200" /><div><p className="data-label text-blue-200/75">Next tier</p><h3 className="mt-1 font-semibold text-white">{nextUnlock.achievementTitle} · {nextUnlock.tierLabel}</h3><p className="mt-1 text-sm text-blue-100/70">{nextUnlock.criteria}</p></div></div><div className="flex items-center gap-3"><div className="h-2 w-24 overflow-hidden rounded-full bg-slate-950/60"><div className="h-full rounded-full bg-blue-300" style={{ width: `${nextUnlock.progressPercent}%` }} /></div><span className="text-sm font-semibold text-blue-100">{nextUnlock.progressPercent}%</span></div></div>}
  <div className="grid gap-4 p-5 sm:p-7 xl:grid-cols-2">{achievements.map((achievement) => { const Icon = ICONS[achievement.id as keyof typeof ICONS] ?? Medal; return <article key={achievement.id} className="rounded-2xl border border-white/10 bg-white/[0.025] p-4 transition hover:border-blue-300/25 hover:bg-blue-400/[0.035]"><div className="flex items-start gap-3"><span className="inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-blue-300/20 bg-blue-400/[0.08] text-blue-200"><Icon className="h-5 w-5" /></span><div className="min-w-0"><h3 className="font-semibold text-white">{achievement.title}</h3><p className="mt-1 text-sm leading-5 text-white/60">{achievement.description}</p></div></div><div className="mt-5 grid gap-2 sm:grid-cols-3">{achievement.tiers.map((tier) => { const style = TIER_STYLE[tier.tier]; return <div key={tier.tier} aria-label={`${achievement.title} ${tier.label}: ${tier.earned ? "earned" : "in progress"}`} className={`relative overflow-hidden rounded-xl border p-3 ${tier.earned ? style.shell : "border-white/10 bg-slate-950/40 text-white/55"}`}><div className="flex items-center justify-between gap-2"><span className={`inline-flex h-6 min-w-6 items-center justify-center rounded-md px-1.5 text-[10px] font-bold uppercase tracking-[.1em] ${tier.earned ? style.mark : "bg-white/[0.06] text-white/50"}`}>{tier.label.slice(0, 1)}</span>{tier.earned ? <BadgeCheck className="h-4 w-4 text-white" aria-label="Earned" /> : <ChevronRight className="h-4 w-4 text-white/35" />}</div><p className="mt-3 min-h-10 text-xs leading-5">{tier.criteria}</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-black/30"><div className={`h-full rounded-full ${tier.earned ? style.bar : "bg-white/20"}`} style={{ width: `${tier.progressPercent}%` }} /></div><p className="mt-2 text-[11px] opacity-75">{tier.earned ? "Collected" : `${tier.progressPercent}% complete`}</p></div>; })}</div></article>; })}</div></section>;
}
