import { Activity, TrendingDown, TrendingUp } from "lucide-react";

type Point = { index: number; changePercent: number };
function Sparkline({ points, color }: { points: Point[]; color: string }) {
  if (points.length < 2) return <div className="flex h-28 items-center justify-center text-xs text-slate-500">Awaiting more BBX ticks</div>;
  const values = points.map((point) => point.index); const min = Math.min(...values); const max = Math.max(...values); const range = Math.max(max - min, 0.1);
  const path = points.map((point, index) => `${index ? "L" : "M"}${(index / (points.length - 1)) * 100},${94 - ((point.index - min) / range) * 84}`).join(" ");
  return <svg viewBox="0 0 100 100" preserveAspectRatio="none" className="mt-4 h-28 w-full overflow-visible" aria-label="Performance graph"><path d="M0,94 L100,94" stroke="rgba(148,163,184,.2)" strokeWidth="1" vectorEffect="non-scaling-stroke"/><path d={path} fill="none" stroke={color} strokeWidth="2.2" vectorEffect="non-scaling-stroke"/></svg>;
}
export function BbxPerformanceGraphs({ performance }: { performance: { market: Point[]; affectedSectors: Array<{ sector: string; headline: string; series: Point[] }> } }) {
  const marketChange = performance.market.at(-1)?.changePercent ?? 0;
  return <section className="mt-8 grid gap-5 xl:grid-cols-[1.35fr_1fr]"><div className="editorial-panel p-6"><div className="flex items-start justify-between gap-4"><div><p className="data-label">Exchange trajectory</p><h2 className="mt-1 text-xl font-semibold text-white">Whole BBX market</h2><p className="mt-1 text-sm text-slate-400">Equal-weighted fictional market performance across recorded BBX ticks.</p></div><div className={`flex items-center gap-1 font-mono text-sm font-semibold ${marketChange >= 0 ? "text-emerald-300" : "text-rose-300"}`}>{marketChange >= 0 ? <TrendingUp className="h-4 w-4" /> : <TrendingDown className="h-4 w-4" />}{marketChange >= 0 ? "+" : ""}{marketChange.toFixed(2)}%</div></div><Sparkline points={performance.market} color={marketChange >= 0 ? "#34d399" : "#fb7185"}/></div><div className="editorial-panel p-6"><div className="flex items-start gap-3"><Activity className="mt-0.5 h-5 w-5 text-blue-300"/><div><p className="data-label">News influence</p><h2 className="mt-1 text-xl font-semibold text-white">Affected sectors</h2><p className="mt-1 text-sm text-slate-400">Recent fictional Blue’s News events and the related sector trajectories.</p></div></div><div className="mt-4 space-y-3">{performance.affectedSectors.length ? performance.affectedSectors.map((sector) => <details key={sector.sector} className="rounded-md border border-white/10 bg-slate-950/30 p-3" open><summary className="cursor-pointer list-none"><p className="text-sm font-semibold text-white">{sector.sector}</p><p className="mt-1 line-clamp-1 text-xs text-slate-400">{sector.headline}</p></summary><Sparkline points={sector.series} color="#60a5fa"/></details>) : <p className="rounded-md border border-white/10 bg-slate-950/30 p-4 text-sm text-slate-400">News-affected sector graphs appear after fictional sector events are published.</p>}</div></div></section>;
}
