import { useState } from "react";
import { ChevronDown, ClipboardList, Loader2 } from "lucide-react";
import { trpc } from "@/lib/trpc";

export function IndividualMockExamHistory() {
  const { data: history = [], isLoading } = trpc.mockExams.getIndividualHistory.useQuery();
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const detail = trpc.mockExams.getIndividualHistoryDetail.useQuery({ sessionId: selectedId ?? 0 }, { enabled: selectedId !== null });

  return <aside className="editorial-panel mt-6 p-5 lg:mt-0"><div className="flex items-start justify-between gap-3"><div><p className="data-label">Individual exam history</p><h2 className="mt-1 text-lg font-semibold text-white">Past readiness checks</h2></div><ClipboardList className="h-5 w-5 text-blue-300" /></div>{isLoading ? <div className="mt-5 flex items-center gap-2 text-sm text-slate-400"><Loader2 className="h-4 w-4 animate-spin" />Loading history…</div> : history.length === 0 ? <p className="mt-5 text-sm leading-relaxed text-slate-400">Completed individual mock exams will appear here with their study recommendations.</p> : <div className="mt-5 space-y-2">{history.map((item) => <button key={item.id} type="button" onClick={() => setSelectedId(selectedId === item.id ? null : item.id)} className={`w-full rounded-md border p-3 text-left transition ${selectedId === item.id ? "border-blue-400/45 bg-blue-500/10" : "border-white/10 bg-white/[0.025] hover:border-blue-400/30"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-white">{item.cluster}</p><p className="mt-1 text-xs text-slate-400">{new Date(item.completedAt).toLocaleDateString()} · {item.correctAnswers}/{item.totalQuestions} correct</p></div><span className="font-mono text-sm font-semibold text-blue-200">{item.accuracy}%</span></div></button>)}</div>}{selectedId !== null && <div className="mt-5 border-t border-white/10 pt-4">{detail.isLoading ? <div className="flex items-center gap-2 text-sm text-slate-400"><Loader2 className="h-4 w-4 animate-spin" />Loading PI analysis…</div> : detail.data && <><p className="data-label">PI accuracy</p><div className="mt-2 space-y-2">{detail.data.instructionalAreas.flatMap((area) => area.performanceIndicators.map((pi) => <div key={`${area.instructionalArea}-${pi.performanceIndicator}`} className="rounded-md bg-slate-950/35 px-3 py-2"><p className="text-xs font-medium text-slate-100">{pi.performanceIndicator}</p><p className="mt-1 font-mono text-xs text-slate-400">{pi.accuracy}% · {pi.correct}/{pi.attempted}</p></div>))}</div><p className="mt-4 data-label">Study guide provided</p>{detail.data.studyGuide.length ? <div className="mt-2 space-y-2">{detail.data.studyGuide.map((guide) => <div key={guide.performanceIndicator} className="rounded-md border border-amber-400/20 bg-amber-500/[0.045] px-3 py-2"><p className="text-xs font-medium text-amber-100">{guide.performanceIndicator}</p><p className="mt-1 text-xs text-slate-400">{guide.questions.length} related question{guide.questions.length === 1 ? "" : "s"} selected</p></div>)}</div> : <p className="mt-2 text-xs text-emerald-200">No priority PI study guide was needed.</p>}</>}</div>}</aside>;
}
